version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "testDB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
